### PR TITLE
Change original module renaming to happen lazily when coverage is not reporting

### PR DESCRIPTION
**Pull request by edgurgel**
Second try on speeding up `Mimic.copy`!

If cover is not enabled Mimic will just mark the module to be copied instead of copying it. Once `stub`, `stub_with`,`expect` or `reject` is called the module is actually copied. This means that it will delay as much as possible.

When cover is enabled copying will happen as soon as `Mimic.copy`is called so that there is a clean point where the module is replaced and cover data is not lost.

It also changes the way that `reset` is handled so it runs things in parallel using Tasks. 

I think this has no drawbacks but might need some real tests with real projects out there. No breaking changes also :relieved: 

Hopefully this is a better fix to #32

### CODE REVIEW

**Comment by calvin-kargo** [comment]
I just finished benchmark this PR on my project, and it's the best!

This PR has comparable performance to Mimic 1.5.1 with TDD_MODE=true (which use async Mimic.copy + ondemand copy), and on this PR, there's no noticable difference between using TDD_MODE or not.
```
test: invoiceable_delivery_orders_test.exs
Mimic 1.5.1
TDD_MODE=false, 0m53,435s
TDD_MODE=true, 0m17,719s

Mimic, git branch lazy-rename-take-2
TDD_MODE=false,  0m19,194s
TDD_MODE=true,  0m19,927s

---

test: company_shipments_test.exs
Mimic 1.5.1
TDD_MODE=false, 1m0,287s
TDD_MODE=true,  0m44,086s

Mimic, git branch lazy-rename-take-2
TDD_MODE=false, 0m42,719s
TDD_MODE=true,  0m42,224s
```

**Comment by calvin-kargo** [comment]
however, it seems this PR have stability issue when i am running project wide test, in particular, there's occasional Genserver call timeout error when calling `Mimic.stub` or `Mimic.expect` .

My best guess is, based on understanding of PR, sometime during Mimic.stub / Mimic.expect, Mimic is lazy renaming the module. and lazy renaming of the module takes more than 5 second of default genserver timeout

**Comment by edgurgel** [comment]
Yeah that's a good point. I will need to increase the timeout for all calls now that they can all cause a module to be copied. Glad you tested this ☺️ Thanks!

**Comment by calvin-kargo** [comment]
The error looks like
```
     ** (exit) exited in: GenServer.call(Mimic.Server, {:stub, Publisher, :publish_message, #Function<4.101821072/2 in SubmitReassignmentRequestTest.__ex_unit_setup_2/1>, 2, #PID<0.13304.0>}, 5000)
         ** (EXIT) time out
     stacktrace:
       (elixir 1.13.3) lib/gen_server.ex:1030: GenServer.call/3
       (mimic 1.5.2) lib/mimic.ex:126: Mimic.stub/3
        ...
```

**Comment by edgurgel** [comment]
Ok I've pushed a change that uses 60 seconds for all calls. I didn't use infinity just so if we have a bug it won´t actually hang there forever and it will be easier to find out what is going on.

**Comment by calvin-kargo** [comment]
make sense to set it at 60, but how about making it configurable so that specific project could increase timeout if needed?

**Comment by calvin-kargo** [comment]
though my project doesn't have any genserver call error after latest change.

**Comment by edgurgel** [comment]
> make sense to set it at 60, but how about making it configurable so that specific project could increase timeout if needed?

Yeah fair point. I will change it to be an application env that can be changed just in case that's not enough.

**Comment by edgurgel** [comment]
I will let this PR sit here for another day or two and release a new version. I think the last part needed (probably a separate PR) now is to allow the Server to not block the whole server while copying a module and it should be as fast as your TTD_MODE

**Pull request merged**
